<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/ & http://www.werger.org
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'about' => 'Derbarde',
		'add_user_x_favorites' => '"^" Bişopîne',
		'approve_required' => 'Kerema xwe hêvîya erê kirina hesabê xwe bisekinin ango ^1zêdetirîn agahî bidin.^2.',
		'approve_title' => 'Ev endam hêvîya erê kirinê ye. ',
		'approve_user_button' => 'Vî endamê erê bike.',
		'approved_user' => 'Endam hatîye piştrast kirin',
		'avatar_default' => 'Rawêj(Default)',
		'avatar_gravatar' => '^1Gravatar^2\'ê nîşan bide',
		'avatar_label' => 'Wêneya endam:',
		'avatar_none' => 'Nîne',
		'block_user_button' => 'Endamê asteng bike',
		'blocked_users' => 'Endamên astenkirî',
		'category_level_add' => ' - ^1Li gor kategorî cîyawazî (level) biafirîne^2',
		'category_level_in' => 'Kategorîyek hilbijêre:',
		'category_level_label' => 'Çîyawazîyê bilind bike:',
		'category_level_none' => 'Çîyawazî bilinkirin nîne. ',
		'change_email_link' => ' - ^1Emaîlê biguhirîne^2',
		'change_password' => 'Password biguhirîne',
		'confirm_button' => 'Emaîlê erê bike.',
		'confirm_complete' => 'Sipas - emaîla te hate erê kirin.',
		'confirm_emailed' => 'Lînka erê kirinê hate şandin. Ji bo erê kirinê lînka ku ji were hate şandin pê lêbikin.',
		'confirm_required' => 'Lînka erê kirinê hate şandin. Ji bo erê kirinê lînka ku ji were hate şandin pê lêbikin ango ^1Girêdankek din bişîne^2.',
		'confirm_title' => 'Erê kirina emaîl',
		'confirm_wrong_log_in' => 'Kod ne raste - ji bo girêdankek nû kereme xwe ^1Têkevin hesabê xwe^2.',
		'confirm_wrong_resend' => 'Kod ne raste - ji bo girêdankek nû kereme xwe pê li jêrê bikin',
		'delete_user_button' => 'Vî kesê jê bibe',
		'edit_profile' => 'Profîlamin tomar bike',
		'edit_user_button' => 'Vî kesî sererast bike',
		'email_code_another' => 'Kodê nûva bişîne',
		'email_code_emailed' => 'Kod hate şandin.Kerema xwe li emaîla xwe mêzebike.',
		'email_code_label' => 'Kod:',
		'email_code_wrong' => 'Kod ne raste',
		'email_confirmed' => 'Kod hat erê kirin',
		'email_exists' => 'Ev maîl ewilde bî alîyê kesek din tên bikaranîn.',
		'email_handle_label' => 'Emaîl û navê endam:',
		'email_invalid' => 'Ev emaîl ne raste - kerema xwe rast binvîsin.',
		'email_label' => 'Emaîl:',
		'email_not_confirmed' => 'Hê nehatîye erê kirin',
		'email_please_confirm' => 'Kerema xwe ^5erê bikin^6',
		'email_required' => 'Emaîl divê',
		'forgot_link' => 'Min şîfra xwe bîrvakir ?',
		'full_name' => 'Nav',
		'handle_blocked' => 'Ev nav nehat erê kirin.Navek din biceribîne',
		'handle_empty' => 'Navê endam vala nabe',
		'handle_exists' => 'Ev nav aliyê kesek dinve hatîye hildan, yeke din biceribîne',
		'handle_has_bad' => 'Navê endam: di nava navde ^ nebin',
		'handle_label' => 'Navê endam:',
		'hide_all_user_button' => 'Hemû peyamên ji alîyên vî kesê ve tên weşandin veşêre',
		'last_login_label' => 'Têketina dawî:',
		'last_write_label' => 'Tevgera dawî:',
		'level_admin' => 'Rêvebir',
		'level_editor' => 'Edîtor',
		'level_expert' => 'Pispor',
		'level_for_category' => 'Ji bo ^2 ^1',
		'level_in_general' => 'Gelemperî',
		'level_moderator' => 'Moderator',
		'level_super' => 'Rêvebirê Bilind',
		'location' => 'Ji ku',
		'log_in_to_access' => 'Ji bo hesab, kerema xwe ^1Pê lêke û Têkevê^2.',
		'login_button' => 'Erê bike',
		'login_limit' => 'Gelek ceribandinên ji bo têketinê pêk hat - kerema xwe nav saetekîde dîsa biceribînin.',
		'login_title' => 'Têkevinê.',
		'mass_mailings' => 'Maîlên hevra:',
		'mass_mailings_explanation' => 'Bibe kiryarê maîlên ku ji herkesîra tê şandin.',
		'member_for' => 'Dema endambûnê:',
		'member_type' => 'Cor:',
		'new_password_1' => 'Şîfra nû:',
		'new_password_2' => 'Dûbareya şîfra nû:',
		'no_blocked_users' => 'Kesên ku hatine astenkirin nîne',
		'no_permission' => 'Ji bo vî pêvajoyê destûr tune',
		'old_password' => 'Şîfra kevin:',
		'only_shown_admins' => '(Tenê rêvebir dikare bibînin)',
		'only_shown_editors' => '(Tenê edîtor û yên ser wî/ê re dikare bibînin)',
		'only_shown_experts' => '(Tenê pispor û yên ser wî/ê re dikare bibînin)',
		'only_shown_moderators' => '(Tenê moderator û rêvebir dikarin bibînin)',
		'password_changed' => 'Şîfre hat guhartin.',
		'password_label' => 'Şîfre:',
		'password_min' => 'Şîfre kêmtirîn divê ^ karakter bibe',
		'password_mismatch' => 'Herdû şîfre jihev nagrin.',
		'password_none' => 'Qet yek nîne. Ji bo rasterast têketinê şîfrekî binvîsin.',
		'password_sent' => 'Şîfrateyê nû bi rêya maîl hate şandin.',
		'password_to_set' => 'Kerema xwe li sepana "Agahîyên min" de çêbikin.',
		'password_wrong' => 'Şîfre ne raste',
		'private_messages' => 'Peyamên taybet:',
		'private_messages_explanation' => 'Destûrê bide endaman ji bo ku bikaribin maîl bişînin. (Nikarin maîlate bibînin)',
		'profile_saved' => 'Profîl hat tomar kirin.',
		'register_button' => 'Tomarê biqedîne',
		'register_limit' => 'Gelek kes tomar bûn . Kerema xwe qasek şûnda dîsa biceribînie.',
		'register_suspended' => 'Tomara endamên nû ji bo qasek hate asten kirin.',
		'register_title' => 'Tomara endamek nû',
		'registered_label' => 'Tomarbûn:',
		'registered_user' => 'Tomar bûyî',
		'remember' => 'Bibîr bîne',
		'remember_label' => 'Li ser vî kombersê min bibîr bîne',
		'remove_avatar' => 'Avatarê jê bibe:',
		'reset_title' => 'Bîranîna şîfreyê',
		'save_profile' => 'Profîlê tomar bike',
		'save_user' => 'Vî kesê tomar bike',
		'send_confirm_button' => 'Girêdanke erêkirinê bişîne',
		'send_reset_button' => 'Daxwaza şifre bîranîn bişîne',
		'send_reset_note' => 'Maîlekî derbarê zanyarîyende bê şandin.',
		'special_users' => 'Endamên taybet',
		'terms_not_accepted' => 'Divê bê nîşan kirin.',
		'unblock_user_button' => 'Astenga kesan rabike',
		'unsubscribe' => 'Kiryarîyê betal bike:',		
		'unsubscribe_complete' => 'Kiryarîya ji bo maîlên hevra ji aliyên ^0 va hate betal kirin.Ser daxwazê ^1Hesab^2 dikarî bibî kiryar.',
		'unsubscribe_title' => 'Betalîya kiryartîyê',
		'unsubscribe_wrong_log_in' => 'Kod ne raste - ji bo betalkirina kiryarê ^1Tomar bibe^2',
		'user_blocked' => '(Astengkirî)',
		'user_not_found' => 'Ev kes nehat dîtin',
		'wall_posts' => 'Peyamên profîlê:',
		'wall_posts_explanation' => 'Destûr bide kesan ji bo ku binvîsin profîla te (Emaîlê jitere were şandin)',
		'website' => 'Navşîna malpera te',
		'x_ago_from_y' => '^1 ewil ji IP\'a ^2',
	);
