<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/ & http://www.pirsname.com

	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => '1 bersiv',
		'a_convert_to_c' => 'Vi bersivê bizvirîne şîrovekî',
		'a_convert_to_c_on' => 'Vi bersivê bizvirîne şîrovekî:',
		'a_convert_warn' => 'Hişyarî: ev guhestin paşve nayê hildan',
		'a_convert_warn_cs' => 'Hişyarî: ev guhertin paşve nayê hildan û şîroveyên bersivê jî yê were guhestin.',
		'a_notify_email' => 'Ku bersivamin were bijartin ji minre emaîl bişîne vir :',
		'a_notify_label' => 'Ku bersivamin were bijartin ji minre emaîl bişîne vir',
		'a_notify_x_label' => 'Ku bersivamin were bijartin ji minre emaîl bişîne vir (^)',
		'a_waiting_your_approval' => 'Ev bersiv hêvîya erê kirina te ye.',
		'a_your_waiting_approval' => 'Piştê kontrol kirina bersiva te , yê qasek şûnda were erê kirin.',
		'add_answer_button' => 'Bibersivîne',
		'add_comment_button' => 'Bişîne',
		'add_q_favorites' => 'Vi pirsê bişopîne',
		'anon_name_label' => 'Navekî ku dixwazî bê dîtin (Li gor daxwazê):',
		'answer_button' => 'bersiv',
		'answer_limit' => 'Me gelek bersiv hilda - nav saetekî da dîsa bicebiribînin.',
		'answer_must_be_approved' => 'Ji bo bersivandinê divê tu bê erê kirin. Kerema xwe ^1Ji bo zêdetirîn agahî bitikînin^2.',
		'answer_must_confirm' => 'Ji bo bersivandinê divê tu bê erê kirin. Kerema xwe ^5emaîla xwe erê bike^6.',
		'answer_must_login' => 'Ji bo bersivandinê divê tu bê erê kirin. Kerema xwe ^1têkeve^2 veya ^3tomar bibe^4.',
		'answer_q_popup' => 'Vî pirsê bibersivîne',
		'approve_a_popup' => 'Vî bersivê erê bike',
		'approve_button' => 'Erê bike',
		'approve_c_popup' => 'Vî şîroveyê erê bike',
		'approve_q_popup' => 'Vî pirsê erê bike',
		'ask_button' => 'Bişîne',
		'ask_follow_from_a' => 'Pirsateyê derbarê vî bersivêdabe:',
		'ask_follow_title' => 'Pirsekî têkildar bipirse',
		'ask_limit' => 'Gelek pirs hatine pirsîn - nav saetekî da dîsa bicebiribînin.',
		'ask_must_be_approved' => 'Ji bo pirsekî bipirsî divê tu bê erê kirin. Kerema xwe ^1Ji bo zêdetirîn agahî bitikînin^2.',
		'ask_must_confirm' => 'Ji bo pirsek bipirsî divê tu bê erê kirin. Kerema xwe ^5emaîla xwe erê bike^6.',
		'ask_must_login' => 'Ji bo pirsîna pirsekî ^1têkevê^2 ango ^3tomar bibe^4.',
		'ask_same_q' => 'Berîya pirsekî bipirsî kerema xwe lê mêzeke gelo ew pirs ewilda hatîye pirsîn an na:',
		'ask_title' => 'Bipirse',
		'c_notify_email' => 'Piştê şîrovamin ku şîrovek din bê kirin ji minre emaîl bişîne:',
		'c_notify_label' => 'Piştê şîrovamin ku şîrovek din bê kirin ji minre emaîl bişîne vir',
		'c_notify_x_label' => 'Piştê şîrovamin ku şîrovek din bê kirin emîalekî bişîne vir  (^)',
		'c_waiting_your_approval' => 'Ev şîrove benda erê kirinê ye',
		'c_your_waiting_approval' => 'Piştê kontrol kirina şîrova te , yê demek kinde bê weşandin.',
		'category_ask_not_allowed' => 'Li vî beşê nikarî pirsekî bişînî.',
		'category_js_note' => 'Ji bo ku beşek hilbijêrî JavaScrîpt divê bê amade kirin',
		'category_required' => 'Kerema xwe beşekî hilbijêre',
		'claim_a_popup' => 'Vî pirsê hilde ser xwe.',
		'claim_button' => 'Min nivîsî',
		'claim_c_popup' => 'Vî şîroveyê hilde ser xwe',
		'claim_q_popup' => 'Vî pirsê hilde ser xwe',
		'clear_flags_button' => 'Gilîyan paxiş bike',
		'clear_flags_popup' => 'Gilîyên hemû endaman paxiş bike',
		'close_button' => 'Bigre',
		'close_duplicate' => 'Ev pirs hatîye dûbarekirin',
		'close_duplicate_error' => 'Pirsên dûbareyê nehat dîtin - kerema xwe jimareya pirsê ango nava URL da derbas dibe binvîsin, mînak: 123.',
		'close_form_button' => 'Pirsê asê bike (qilf)',
		'close_form_title' => 'Vî pirsê Pirsê asê bike (qilf)',
		'close_original_note' => 'Jimareya pirsê ango nava URLyêda derbas dibe , mînak: 123.',
		'close_original_title' => 'URL ya orjînal:',
		'close_q_popup' => 'Ji bo bersivê nû vî pirsê bigre',
		'close_reason_title' => 'Sedema asê kirina vî pirsê:',
		'closed_as_duplicate' => 'Ev wî pirsê dûbare dike , ji bo wî hat asê kirin:',
		'closed_with_note' => 'bi vî sedemê hate asê kirin:',
		'comment_a_popup' => 'Ji bo vî bersivê şîrovekî bike',
		'comment_button' => 'şîrove',
		'comment_limit' => 'Gelek şîrove hatine kirin - nav saetekîda dîsa biceribînin',
		'comment_must_be_approved' => 'Ji bo şîrovekirinê divê tu werî erê kirin. Kerema xwe qasek bisekinin ango ^1ji bo zêdetirîn agahî bitikînin^2.',
		'comment_must_confirm' => 'Kerema xwe ji bo şîrovekirinê ^5emaîla xwe erê bike^6.',
		'comment_must_login' => 'Kerema xwe ji bo şîrovekirinê ^1têkeve^2 veya ^3tomar bibe^4.',
		'comment_on_a' => 'Li ser bersiv: ',
		'comment_on_q' => 'Li ser pirsê: ',
		'comment_q_popup' => 'Şîrovekî li ser vî pirsê bike',
		'delete_a_popup' => 'Vî bersivê jê bibe',
		'delete_button' => 'Jê bibe',
		'delete_c_popup' => 'Vî şîroveyê jê bibe',
		'delete_q_popup' => 'Vî pirsê jê bibe',
		'duplicate_content' => 'Ev mîjara te wek qopya tê xûyan.',
		'edit_a_popup' => 'Vî bersivê sererast bike',
		'edit_a_title' => 'Bersivê sererastke',
		'edit_button' => 'sererastke',
		'edit_c_popup' => 'Vî şîroveyê sererast bike',
		'edit_c_title' => 'Şîrovê sererastke',
		'edit_must_confirm' => 'Ji bo sererast kirinê ^5emaîla xwe erê bike^6.',
		'edit_must_login' => 'Ji bo sererast kirinê kerema xwe ^1têkeve^2 ango ^3tomar bibe^4.',
		'edit_q_popup' => 'Vî pirsê sererast bike',
		'edit_q_title' => 'Pirsê sererastke',
		'example_tags' => 'Pêvekerên wek mînak: ',
		'flag_a_popup' => 'Vî bersivê wek reklam ango bêguncav gilî bike',
		'flag_button' => 'Hişyarke',
		'flag_c_popup' => 'Vî şîroveyê wek reklam ango bêguncav gilî bike',
		'flag_hide_button' => 'Gilî bike û veşêre',
		'flag_limit' => 'Gelek bersiv hatine gilî kirin - Kerema xwe nav saetekîda dîsa biceribînin.',
		'flag_must_confirm' => 'Ji bo gilî kirinê divê tu ^5emaîla xwe erê bikî^6.',
		'flag_must_login' => 'Ji bo gilî kirinê ^1Têkevê^2 ango ^3tomar bibe^4.',
		'flag_not_allowed' => 'Destûra hişyarîyê tune',
		'flag_q_popup' => 'Vî pirsê wek reklam ango ne guncav hişyar bike',
		'follow_a_popup' => 'Pirsekî nû û bivî bersivêra têkildar bipirse',
		'follow_button' => 'pirsekî têkildar bipirse',
		'follows_a' => 'derbarê vî bersivêda:',
		'follows_q' => 'Derbarê pirsêda:',
		'hide_a_popup' => 'Vî bersivê veşêre',
		'hide_button' => 'Veşêre',
		'hide_c_popup' => 'Vî şîroveyê veşêre',
		'hide_q_popup' => 'Vî pirsê veşêre',
		'matching_tags' => 'Pêvekerên ewilî: ',
		'max_tags_x' => 'Zêdetirîn ji bo ^ pêvekera destûr hatîye dayîn',
		'min_tags_x' => 'Kerema xwe kêmtirîn ^ pêveker(tag) binvîsin.',
		'notify_email_note' => 'Emaîla te tenê ji bo têkilî û emaîla yê were birakaranîn',
		'q_category_label' => 'Beş(kategorî):',
		'q_content_label' => 'Zêdetir agahî derbarê vî pirsê de :',
		'q_hidden_author' => 'Ev pirs ji alîyê pirsîyar ve hate veşartin.',
		'q_hidden_flagged' => 'Piştê hişyarkirinê hate veşartin',
		'q_hidden_other' => 'Pirs hatîye veşartin',
		'q_notify_email' => 'Ku pirsamin hate bersivandin , min bi rêya emaîl agahdar bike:',
		'q_notify_label' => 'Ku pirsamin hate bersivandin , ji minre emaîlek bişîne.',
		'q_notify_x_label' => 'Ku pirsamin hate bersivandin ji minre (^) emaîlek bişîne.',
		'q_tags_comma_label' => 'Pêveker(tag) - bo ji hev veqetandinê (,) bêhnok bikarbînin:',
		'q_tags_label' => 'Pêveker - Ji bo du pêyva xêzekî (-) navberê da bikarbîne:',
		'q_title_label' => 'Pirs (sernivîs) :',
		'q_waiting_approval' => 'Ev pirs hêvîya erê kirine',
		'q_waiting_your_approval' => 'Ev pirs hêvîya erê kirinê ye.',
		'q_your_waiting_approval' => 'Pirsa we piştê kontrolê û qasek şûnda yê were erê kirin.',
		'recat_button' => 'Beşê biguhirîne',
		'recat_popup' => 'beşa vî pirsê biguhirîne',
		'recat_q_title' => 'beşa vî pirsê biguhirîne',
		'reject_a_popup' => 'Vî bersivê red bike',
		'reject_button' => 'red bike',
		'reject_c_popup' => 'Vî şîroveyê red bike',
		'reject_q_popup' => 'Vî pirsê red bike',
		'remove_q_favorites' => 'Vî pirsê ji şopamin bibe',
		'reopen_button' => 'Nûva biweşîne',
		'reopen_q_popup' => 'Vî pirsê nûva biweşîne',
		'reply_button' => 'Bibersivîne',
		'reply_c_popup' => 'Şîroveyê bibersivîne',
		'reshow_a_popup' => 'Vî bersivê dîsa biweşîne',
		'reshow_button' => 'Dîsa biweşîne',
		'reshow_c_popup' => 'Vî şîroveyê dîsa biweşîne',
		'reshow_q_popup' => 'Vî pirsê dîsa biweşîne',
		'retag_button' => 'Pêvekerê rastbike',
		'retag_cat_popup' => 'Beş û pêvekerê vî pirsê biguhirîne',
		'retag_popup' => 'Pêvekerê(Tag) vî pirsê biguhirîne',
		'retag_q_title' => 'Pirsê nûva pêveker bike',
		'save_silent_label' => 'Nivîsa ku "ev pirs hatîye tomar kirin" veşêre û biweşîne', 
		'select_popup' => 'Wek bersiva herî baş hilbijêre.',
		'select_text' => 'Bersiva Baştirîn',
		'show_1_comment' => '1 şîrovekî nîşan bide',
		'show_1_previous_comment' => '1 şîrovekî ewilîn nîşan bide',
		'show_x_comments' => '^ şîrova bide nîşan',
		'show_x_previous_comments' => '^ şîroveyên ewilîn bide nîşan',		
		'unflag_button' => 'Hîşyarîyê rake',
		'unflag_popup' => 'Hîşyarîya ku te lê zêde kirîye rake',
		'unselect_popup' => 'Ji bo rakirina bijarteyê pê lêke.',
		'x_answers_title' => '^ bersiv',
		'your_answer_title' => 'Bersiva te',
		'your_comment_a' => 'Ji bo vî bersivê şîrova te:',
		'your_comment_q' => 'Ji bo vî pirsê şîrova te:',
	);
