<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/ & http://www.pirsname.com

	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 bersivek',
		'1_comment' => '1 şîrovek',
		'1_day' => '1 rojek',
		'1_disliked' => '1 unlike',
		'1_flag' => '1 gilî',
		'1_hour' => '1 saet',
		'1_liked' => '1 like',
		'1_minute' => '1 xulek',
		'1_month' => '1 meh',
		'1_point' => '1 pûanek',
		'1_question' => '1 pirs',
		'1_second' => '1 sanîye',
		'1_tag' => '1 pêvekerek',
		'1_user' => '1 endamek',
		'1_view' => '1 dîtinek',
		'1_vote' => '1 dengek',
		'1_week' => '1 heftek',
		'1_year' => '1 salek',
		'_decimal_point' => '.',
		'_millions_suffix' => 'm',
		'_thousands_separator' => ',',
		'_thousands_suffix' => 'k',
		'add_category_x_favorites' => 'Bêşa "^" bişopîne',
		'add_favorites' => 'Bişopîne',
		'add_tag_x_favorites' => 'Pêveker(tag) "^" bişopîne',
		'all_categories' => '',
		'anonymous' => 'mêvan',
		'answer_edited' => 'bersiv hate nû kirin',
		'answer_reshown' => 'bersivê dîsa bide nîşan',
		'answer_selected' => 'bersiva bijarte',
		'answered' => 'bersivandin',
		'answered_qs_in_x' => 'li nav "^" pirsên zêdetir hatine bersivandin',
		'answered_qs_title' => 'Pirsên herî zêde hatine bersivandin',
		'asked' => ' hate pirsîn',		
		'asked_related_q' => 'Pirsekî têkîldar hate pirsîn',
		'by_x' => 'Ji aliyê ^',
		'cancel_button' => 'Betal',
		'closed' => 'girtî',
		'comment_edited' => 'şîroveya sererastkirî',
		'comment_moved' => 'şîrove hat guhastin',
		'comment_reshown' => 'şîrove nûva hate weşandin.',
		'commented' => 'şîrove kirin',
		'date_day_min_digits' => '1',
		'date_format_other_years' => '^day, ^month, ^year',
		'date_format_this_year' => '^day, ^month, ^day',
		'date_month_1' => 'Tebax',
		'date_month_10' => 'Kewçêr',
		'date_month_11' => 'Mijdar',
		'date_month_12' => 'Berfanbar',
		'date_month_2' => 'Reşemî',
		'date_month_3' => 'Adar',
		'date_month_4' => 'Avrêl',
		'date_month_5' => 'Gulan',
		'date_month_6' => 'Pûşper',
		'date_month_7' => 'Tîrmeh',
		'date_month_8' => 'Gelawêj',
		'date_month_9' => 'îlon',
		'date_year_digits' => '4',
		'edited' => 'hate sererast kirin',
		'email_error' => 'Dema emaîl hate şandin pirsgirîkek pêk hat.',
		'field_required' => 'Li vir tiştekî binvîsin',
		'file_upload_limit_exceeded' => 'Mezin bûna dosyayê li ser lîmîtên serverêra ye.',
		'general_error' => 'Pirsgirîkek li ser serverê pêk hat. Kerema xwe dîsa bicebînin.',
		'hidden' => 'Veşartî',
		'highest_users' => 'Endamên ku pûanên zêdetirin hildane',
		'hot_qs_in_x' => 'Pirsên ji bo ^ yên herî popûler ',
		'hot_qs_title' => 'Pirsên ecibandin',
		'image_not_read' => 'Wêne nehate xwendin.Kerema xwe yejî bar bike: ^',
		'image_too_big_x_pc' => 'Wêne pir mezine. Kerema xwe ^%\'ê kêm bike û nûva biceribîne',
		'in_category_x' => 'beşa ^ \'de',
		'ip_address_x' => 'Navnîşana IP ^',
		'logged_in_x' => 'Silav ^',
		'max_length_x' => 'Zêdetirîn divê ^ bibe',
		'max_upload_size_x' => 'Cîhê herî zêde ^',
		'me' => 'ya/yê min', 
		'meta_order' => '^when^where^who^what', // sets order of elements like: <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Kerema xwe zêdetirîn (kêmtirîn ^ pêyv ango tîp)',
		'moved' => 'guhastin',
		'nav_activity' => 'Bîranîn',
		'nav_admin' => 'Rêvebirî',
		'nav_ask' => 'Pirske !',
		'nav_categories' => 'Hemû Beş',
		'nav_feedback' => 'Têkilî',
		'nav_home' => 'Destpêk',
		'nav_hot' => 'Nû',
		'nav_login' => 'Têkevê',
		'nav_logout' => 'Derkeve',
		'nav_most_answers' => 'Yên zêdetirin bersivandin',
		'nav_most_recent' => 'Yên nû',
		'nav_most_views' => 'Yên zêdetirîn hatine dîtin',
		'nav_most_votes' => 'Yên zêdetirîn hatine ecibandin',
		'nav_no_answer' => 'Bê bersiv',
		'nav_no_selected_answer' => 'Yên ku bersivên bijartî nînin',
		'nav_no_upvoted_answer' => 'Bersivên dengê erînî nînin',
		'nav_qa' => 'Destpêk',
		'nav_qs' => 'Pirs',
		'nav_register' => 'Tomar (Qeyd be )',
		'nav_tags' => 'Hemû Tag',
		'nav_unanswered' => 'Bê bersiv',
		'nav_updates' => 'nûjenîyên min',
		'nav_users' => 'Hemû Endam',
		'newest_users' => 'Endamên nû',
		'no_active_users' => 'Endamên online tune',
		'no_answers_found' => 'Bersiv nehatîye afirandin. ',
		'no_answers_in_x' => 'Ji bo "^" bersiv tune',
		'no_categories_found' => 'Beş nehatîye afirandin.',
		'no_category' => 'Bê beş',
		'no_comments_found' => 'Şîrove nehatîye afirandin.',
		'no_comments_in_x' => 'Ji bo "^" şîrove tunene ',
		'no_questions_found' => 'Pirs nehatîye afirandin.',
		'no_questions_in_x' => 'Ji bo "^" pirs nehatîye afirandin.',
		'no_related_qs_title' => 'Pirsên têkildar nehatîye afirandin.',
		'no_results_for_x' => 'Ji bo "^" tu encam nehatîye afirandin.',
		'no_tags_found' => 'Pêveker(Tag) nehatîye afirandin.',
		'no_una_questions_found' => 'Pirsên bê bersiv nehate dîtin.',
		'no_una_questions_in_x' => 'Ji bo "^" bersiv nehatine afirandin.',
		'no_unselected_qs_found' => 'Pirsên bê bijare nehatin dîtin.',
		'no_unupvoteda_qs_found' => 'Pirsên dengê erênî hilnedane , nehate dîtin.',
		'page_label' => 'Rûpel:',
		'page_next' => 'pêş',
		'page_not_found' => 'Rûpel nayê dîtin',
		'page_prev' => 'paş',
		'popular_tags' => 'Pêvekerên pir hatine ecibandî',
		'questions_tagged_x' => 'Ji bo ^ pirsên nû',
		'recategorized' => 'beş hat guhartin',
		'recent_activity_in_x' => 'Ji bo ^ bîranînên nû ',
		'recent_activity_title' => 'Bîranînên nû',
		'recent_as_in_x' => 'Ji bo ^ pirsên nû hatine bersivandin.',
		'recent_as_title' => 'Pirsên dawîde hatine bersivandin',
		'recent_cs_in_x' => 'Ji bo ^ şîroveyên nû ',
		'recent_cs_title' => 'Şîroveyên nû ku lê hatine zêde kirin',
		'recent_qs_as_in_x' => 'Ji bo ^ pirsên nû',
		'recent_qs_as_title' => 'hemû pirs!',
		'recent_qs_in_x' => 'Pirsên nû li ^ hatine zêde kirin ',
		'recent_qs_title' => 'Pirsên nû',
		'related_qs_title' => 'Pirsên têkildar',
		'remove_favorites' => 'Ji şopamin derxe',
		'remove_x_favorites' => '^\' ji bo şopamin derxe',
		'reopened' => 'Dîsa hat vekirin',
		'reshown' => 'Hat nîşan dan',
		'results_for_x' => 'encamên lêgerîna pêyva ^ ',
		'retagged' => 'guhertin',
		'save_button' => 'Hemû guhartinan tomar bike',
		'search_button' => 'Lê bigere',
		'search_explanation' => 'Bi kerema xwe dîsa pêyvekî binvîsin û lê bigerin',
		'search_title' => 'Pirsan bigere',
		'selected' => 'bijartin',
		'send_button' => 'Bişîne',
		'since_x' => '^',
		'suggest_ask' => 'Ji bo destpêkê ^1pirseki bipirse^2.',
		'suggest_category_qs' => 'Ji bo zêdetirîn, ^1Pirsên li ser vî beşê^2 pê lêkin.',
		'suggest_qs' => 'Ji bo zêdetirîn,  pê li ^1hemû lîsta pirsan^2 bikin.',
		'suggest_qs_tags' => 'Ji bo zêdetirîn, ^1hemû pirs^2 ango  ^3tagên ecibandî^4 pê lêkin.',
		'to_x' => 'Bo endam ^ ',
		'unanswered_qs_in_x' => 'ji bo ^ yên ku nehatine bersivandin',
		'unanswered_qs_title' => 'Pirsên nû û bê bersiv',
		'unselected_qs_in_x' => ' pirsên li ^ yên bijartî û bê bersiv',
		'unselected_qs_title' => 'Pirsên ne bijartî û yên bê bersiv',
		'unupvoteda_qs_in_x' => 'Ji bo ^ yên ku dengê erênî hilnedane.',
		'unupvoteda_qs_title' => 'Pirsên nû ku dengê erênî hilnedane.',
		'upload_limit' => 'Gelek giranî li serverê çêbû -  kerema xwe nav saetekîda dîsa bicerîbînin.',
		'view_q_must_be_approved' => 'Ji bo pirsên li ser rûpelan divê hesabê we bê erê kirin. Kereme xwe çendek bisekinin ango ^1zêdetirîn agahî bidin.^2.',
		'view_q_must_confirm' => 'Ji bo pirsên li ser rûpelan ^5emaîla xwe erê bikin.^6.',
		'view_q_must_login' => 'Ji bo pirsên li ser rûpelan ^1Têkeve^2 ango ^3Tomar bibe^4.',
		'viewed_qs_in_x' => 'Pirsên li nav ^ yên ku zêdetirîn hatin dîtin.',
		'viewed_qs_title' => 'Pirsên zêdetir hatine dîtin.',
		'vote_disabled_approve' => 'Ji bo dengdanê hesabê xwe erê bikin.',
		'vote_disabled_down' => 'Dengê nerênî ji bo hin kesan vekirîye.',
		'vote_disabled_down_approve' => 'Ji bo dengê nerênî divê hûn hesabên xwe erê bikin.',
		'vote_disabled_hidden_a' => 'Ji bo bersivên veşartî deng nayê dayîn.',
		'vote_disabled_hidden_post' => 'Ji bo peyamên veşartî deng nayê dayîn.',
		'vote_disabled_hidden_q' => 'Ji bo pirsên veşartî deng nayê dayîn.',
		'vote_disabled_level' => 'Dengdayîn ji bo hinek kesan vekirîye.',
		'vote_disabled_my_a' => 'Tu nikarî ji bo bersivê xwe deng bidî',
		'vote_disabled_my_post' => 'Tu nikarî ji bo peyamê xwe deng bidî.',
		'vote_disabled_my_q' => 'Tu nikarî ji bo pirsê xwe deng bidî.',
		'vote_disabled_q_page_only' => 'Ji bo dengdayînê li pirsê mêze bike',
		'vote_disabled_queued' => 'Hûn dikarin tenê ji bo peyamên erênî deng bidin.',
		'vote_down_must_confirm' => 'Ji bo denghildanê kerema xwe ^5emaila xwe erê bikin^6.',
		'vote_down_popup' => 'Ji bo dengê nerênî bitikîne',
		'vote_limit' => 'Gelek deng hate dayîn - çendek şûnda dîsa biceribînin',
		'vote_must_confirm' => 'Ji bo dengdayînê kerema xwe ^5emaila xwe erê bikin^6.',
		'vote_must_login' => 'Ji bo deng dayîne kerema xwe ^1Têkevê^2 ango ^3Tomar bibe^4.',
		'vote_not_allowed' => 'Ji bo dengdayînê destûr tune.',
		'vote_up_popup' => 'Ji bo dengê erênî bitikîne',
		'voted_down_popup' => 'Te dengê nerênî dabû - Ji bo vî dengê hildî , bitikîne',
		'voted_qs_in_x' => 'Pirsên nava "^" yên zêdetirin deng hildaye ',
		'voted_qs_title' => 'Pirsên zêdetirin deng hildaye',
		'voted_up_popup' => 'Te dengê erênî dabû - Ji bo vî dengê hildî , bitikîne',
		'written' => 'nivîsandin', // blank in English - placeholder for other languages
		'x_ago' => '^ ewil',
		'x_answers' => '^ bersiv',
		'x_comments' => '^ şîrove',
		'x_days' => '^ roj',
		'x_disliked' => '^ unlike',
		'x_flags' => '^ gilî',
		'x_hours' => '^ saet',
		'x_liked' => '^ like',
		'x_minutes' => '^ xulek',
		'x_months' => '^ meh',
		'x_points' => '^ pûan',
		'x_questions' => '^ pirs',
		'x_seconds' => '^ sanîye',
		'x_tags' => '^ pêveker',
		'x_users' => '^ endam',
		'x_views' => '^ dîtin',
		'x_votes' => '^ deng',
		'x_weeks' => '^ hefte',
		'x_years' => '^ sal',
	);
