<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/ & http://www.turksdesk.org

	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'block_ip_button' => '(IP) a wê(î) asteng bike',
		'browse_categories' => 'Tu niha hemû kategorîyan dibînî',
		'captcha_approve_fix' => 'Ev pejirandin piştê ku hesabê te hat erê kirin nayê dîtin.',
		'captcha_confirm_fix' => 'Ji pêşerojê ku tu naxwazî vî sepanê dîsa bibînî, kerema xwe ^5emaîla xwe erê bikin^6.',
		'captcha_error' => 'Kerema xwe sepana spamê erê bikin.',
		'captcha_label' => 'Parêzerîya spam:',
		'captcha_login_fix' => 'Ji pêşerojê ku tu naxwazî vî sepanê dîsa bibînî, kerema xwe ^1Têkevin malperê^2 ango ^3Tomar bibe^4.',
		'feed_a_edited_prefix' => 'Bersiv hate sererast kirin: ',
		'feed_a_prefix' => 'Hate bersivandin: ',
		'feed_a_reshown_prefix' => 'Bersiv nûva hat nîşandan: ',
		'feed_a_selected_prefix' => 'Peyam hat hilbijartin: ',
		'feed_c_edited_prefix' => 'Şîrove hat sererast kirin: ',
		'feed_c_moved_prefix' => 'Şîrove hat guhastin: ',
		'feed_c_prefix' => 'Hat şîrove kirin: ',
		'feed_c_reshown_prefix' => 'Şîrove nûva hat nîşandan: ',
		'feed_closed_prefix' => 'Hate girtin: ',
		'feed_edited_prefix' => 'Hate sererast kirin: ',
		'feed_hidden_prefix' => 'Hat veşartin: ',
		'feed_not_found' => 'Qet peyam nehat dîtin',
		'feed_recategorized_prefix' => 'Ji nûva hate kategorîzekirin: ',
		'feed_reopened_prefix' => 'Ji nûva hate vekirin: ',
		'feed_reshown_prefix' => 'Ji nûva hate nişandan: ',
		'feed_retagged_prefix' => 'Ji nûva tag hate dayîn : ',
		'feedback_email' => 'Emaîla te: (ser daxwazê)',
		'feedback_empty' => 'Ev cîh ji bo peyam,fikir û ramanê ku tu dixwazî binvisî ye.',
		'feedback_message' => 'Ji bo ^ peyama xwe binvîse vir:',
		'feedback_name' => 'Navê te: (ser daxwazê)',
		'feedback_sent' => 'Peyam hate şandin sipas.',
		'feedback_title' => 'Peyam (kerema xwe fikir, raman û rexnekî ) bişînin.',
		'form_security_again' => 'Ji bo erê kirinê dîsa pê lêkin.',
		'form_security_reload' => 'Kerema xwe rûpelê nû bikin.',
		'hide_all_ip_button' => 'Hemû tevgerên vî IP\"ê veşêre.',
		'host_name' => 'Navê host:',
		'inbox' => 'Peyamên hatine',
		'matches_blocked_ips' => 'Ev IP , bi IP ên ku hatine asteng kirin ji hev digrin:',
		'message_empty' => 'Kerema xwe peyama ku tu dixwazî bişînî binvîse.',
		'message_explanation' => 'Ev wek ji ^ wek emaîl bê şandin. Emaîla te ji aliyê wê(î) nayê dîtin ku tu nava peyamde nenvîsî.',
		'message_for_x' => 'Ji bo ^ peyamete:',
		'message_limit' => 'Gelek peyam hatine şandin , kerema xwe qasek şûnda dîsa biceribînin',
		'message_must_login' => 'Ji bo peyamek taybet ^1Têkeve malperê^2 ango ^3Tomar bibe^4.',
		'message_recent_history' => 'Peyamên navbera min û ^ de/da',
		'message_sent' => 'Peyama jêrê hate şandin.',
		'more_favorite_qs' => 'Ji bo zêdetirîn pirs...',
		'more_favorite_tags' => 'Ji bo zêdetirîn tag...',
		'more_favorite_users' => 'Ji bo zêdetirîn kes...',
		'my_favorites_title' => 'Tiştên dişopînî',
		'nav_all_my_updates' => 'Hemû tevgerên min',
		'nav_my_content' => 'Naverokên min',
		'nav_my_details' => 'Agahîyên min',
		'nav_my_favorites' => 'Tevgerên dişopînim',
		'nav_user_activity' => 'Tevgerên nû',
		'nav_user_as' => 'Hemû bersiv',
		'nav_user_pms' => 'Peyamên taybet',
		'nav_user_qs' => 'Hemû pirs',
		'nav_user_wall' => 'Profîl',
		'next_step' => 'Gava dûre',
		'no_activity_from_x' => 'Tevgerên ^ nîne',
		'no_favorite_categories' => 'Qet (hîç) "KATEGORÎ" nehatîye şopandin',
		'no_favorite_qs' => 'Qet (hîç) "PIRS" nehatîye şopandin',
		'no_favorite_tags' => 'Qet (hîç) "TAG" nehatîye şopandin',
		'no_favorite_users' => 'Qet (hîç) "KES" nehatîye şopandin',
		'no_recent_updates' => 'Tevgerên ku hatine rojane kirin nîne',
		'no_updates_content' => 'Tevgerên nû ji bo naverokên min nîne',
		'no_updates_favorites' => 'Tevgerên ku ez dişopînim nîne',
		'outbox' => 'Peyamên hatine şandin',
		'pm_inbox_title' => 'peyamên hatine hildan',
		'pm_outbox_title' => 'Peyamên hatine şandin',
		'private_message_title' => 'Peyamekî bişîne',
		'recent_activity_from_x' => 'Tevgerên nû ji alîyê ^',
		'recent_updates_content' => 'Tevgerên derbarê naverokêminde',
		'recent_updates_favorites' => 'Tevgerên ji bo tiştên ku ez dişopînim',
		'recent_updates_title' => 'Tevgerêminên nû',
		'site_in_maintenance' => 'Malpera me ji bo qasek navber da xebatê - Kerema xwe çendek şûnda dîsa biceribînin.',
		'suggest_favorites_add' => 'Ji bo şopandina "KES" ,"KATEGORÎ","PIRS","TAG" kî pê li FOLLOW-UNFOLLOW bike.',
		'suggest_update_favorites' => 'Ji bo zêdetirîn pêşnîyar, çend tiştan ^1BIŞOPÎNIN^2.',
		'unblock_ip_button' => 'Astengîya (IP) rake',
		'your_a_commented' => 'bersivate hate şîrove kirin.',
		'your_a_edited' => 'Bersivate hate sererast kirin.',
		'your_a_hidden' => 'Bersivate hate veşartin.',
		'your_a_questioned' => 'Li ser bersivê hate pirsîn',
		'your_a_reshown' => 'Bersivate nûva hatîya şandin.',
		'your_a_selected' => 'Bersivate hate hilbijartin.',
		'your_c_edited' => 'Şîrove hatîye sererast kirin',
		'your_c_followed' => 'Şîrova te hate şopandin',
		'your_c_hidden' => 'Şîrove hatîye veşartin',
		'your_c_moved' => 'Şirove hatîye guhastin',
		'your_c_reshown' => 'Şîrovete nûva hate şandin',
		'your_q_answered' => 'Pirsate hatîye bersivandin',
		'your_q_closed' => 'Pirsate ji weşanê hate rakirin.',
		'your_q_commented' => 'Pirsate hatîye şîrove kirin',
		'your_q_edited' => 'Pirsate hatîye sererast kirin.',
		'your_q_hidden' => 'Pirsate hat veşartin',
		'your_q_recategorized' => 'Ji bo pirsate nûva kategorî hat damezirandin.',
		'your_q_reopened' => 'Pirsate nûva hate şandin',
		'your_q_reshown' => 'Pirsate nûva hate şandin',
		'your_q_retagged' => 'Pirsate nûva hat tag kirin',
	);